#!/bin/bash
# MoAI SessionStart Hook Wrapper - Generated by moai-adk
# Modified to support mode memory and auto-restore
# This script forwards stdin JSON to the moai hook session-start command.
# Project-local hook: .claude/hooks/moai/session-start.sh

# First, run mode handler to restore last mode
session_mode_script="$CLAUDE_PROJECT_DIR/.claude/hooks/moai/session-mode-handler.sh"
if [ -f "$session_mode_script" ]; then
    # Execute mode handler and capture its output
    mode_output=$("$session_mode_script" 2>&1)
    # Log mode restoration
    echo "$mode_output"
fi

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH
if command -v moai &> /dev/null; then
	exec moai hook session-start < "$temp_file" 2>/dev/null
fi

# Try detected Go bin path from initialization
if [ -f "C:/Users/drake.lee/go/bin/moai" ]; then
	exec "C:/Users/drake.lee/go/bin/moai" hook session-start < "$temp_file" 2>/dev/null
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
	exec "$HOME/go/bin/moai" hook session-start < "$temp_file" 2>/dev/null
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
	exec "$HOME/.local/bin/moai" hook session-start < "$temp_file" 2>/dev/null
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
