#!/bin/bash
# MoAI SessionStart Hook Wrapper - Generated by moai-adk
# Extended: Auto-inject DISPATCH Resolution Protocol for team agents after /clear

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Check if this is a team agent session by looking at agent context
# SessionStart provides: source (startup, resume, clear, compact)
source=$(node -e "try{const d=JSON.parse(require('fs').readFileSync('$temp_file','utf8'));console.log(d.source||'unknown')}catch(e){console.log('unknown')}" 2>/dev/null)

# For /clear source, inject DISPATCH Resolution Protocol auto-trigger
if [ "$source" = "clear" ]; then
    # Check if we're in a worktree with an agent
    worktree_branch=$(git branch --show-current 2>/dev/null || echo "")

    case "$worktree_branch" in
        team/team-a)
            protocol="DISPATCH Resolution Protocol START. Step 0: git pull origin main. Step 1: Read .moai/dispatches/active/_CURRENT.md — extract ScheduleWakeup value. Step 2: Find Team A row. Step 3: If IDLE/MERGED, report IDLE + ScheduleWakeup(value). Step 4: If ACTIVE, read DISPATCH and execute immediately. After action: re-read _CURRENT.md, ScheduleWakeup(that value, minimum 300)."
            ;;
        team/team-b)
            protocol="DISPATCH Resolution Protocol START. Step 0: git pull origin main. Step 1: Read .moai/dispatches/active/_CURRENT.md — extract ScheduleWakeup value. Step 2: Find Team B row. Step 3: If IDLE/MERGED, report IDLE + ScheduleWakeup(value). Step 4: If ACTIVE, read DISPATCH and execute immediately. After action: re-read _CURRENT.md, ScheduleWakeup(that value, minimum 300)."
            ;;
        team/coordinator)
            protocol="DISPATCH Resolution Protocol START. Step 0: git pull origin main. Step 1: Read .moai/dispatches/active/_CURRENT.md — extract ScheduleWakeup value. Step 2: Find Coordinator row. Step 3: If IDLE/MERGED, report IDLE + ScheduleWakeup(value). Step 4: If ACTIVE, read DISPATCH and execute immediately. After action: re-read _CURRENT.md, ScheduleWakeup(that value, minimum 300)."
            ;;
        team/team-design)
            protocol="DISPATCH Resolution Protocol START. Step 0: git pull origin main. Step 1: Read .moai/dispatches/active/_CURRENT.md — extract ScheduleWakeup value. Step 2: Find Design row. Step 3: If IDLE/MERGED, report IDLE + ScheduleWakeup(value). Step 4: If ACTIVE, read DISPATCH and execute immediately. After action: re-read _CURRENT.md, ScheduleWakeup(that value, minimum 300)."
            ;;
        team/qa)
            protocol="DISPATCH Resolution Protocol START. Step 0: git pull origin main. Step 1: Read .moai/dispatches/active/_CURRENT.md — extract ScheduleWakeup value. Step 2: Find QA row. Step 3: If IDLE/MERGED, report IDLE + ScheduleWakeup(value). Step 4: If ACTIVE, read DISPATCH and execute immediately. After action: re-read _CURRENT.md, ScheduleWakeup(that value, minimum 300)."
            ;;
        team/ra)
            protocol="DISPATCH Resolution Protocol START. Step 0: git pull origin main. Step 1: Read .moai/dispatches/active/_CURRENT.md — extract ScheduleWakeup value. Step 2: Find RA row. Step 3: If IDLE/MERGED, report IDLE + ScheduleWakeup(value). Step 4: If ACTIVE, read DISPATCH and execute immediately. After action: re-read _CURRENT.md, ScheduleWakeup(that value, minimum 300)."
            ;;
        team/cc)
            protocol="COMMAND CENTER SESSION START. Step 0: git pull origin main. Step 1: Read .moai/dispatches/active/_CURRENT.md — extract CC ScheduleWakeup value. Step 2: Analyze ALL team rows. If all MERGED: gap analysis → create DISPATCH files → git add → git commit → git push origin HEAD:main. Create Gitea issues. ScheduleWakeup(CC value, minimum 300)."
            ;;
        *)
            protocol=""
            ;;
    esac

    if [ -n "$protocol" ]; then
        # Output additionalContext to auto-trigger protocol
        echo "{\"additionalContext\": \"[AUTO-RECOVERY AFTER /clear] $protocol\"}"
        exit 0
    fi
fi

# Default: forward to moai binary
if command -v moai &> /dev/null; then
    exec moai hook session-start < "$temp_file" 2>/dev/null
fi

if [ -f "C:/Users/drake.lee/go/bin/moai" ]; then
    exec "C:/Users/drake.lee/go/bin/moai" hook session-start < "$temp_file" 2>/dev/null
fi

if [ -f "$HOME/go/bin/moai" ]; then
    exec "$HOME/go/bin/moai" hook session-start < "$temp_file" 2>/dev/null
fi

if [ -f "$HOME/.local/bin/moai" ]; then
    exec "$HOME/.local/bin/moai" hook session-start < "$temp_file" 2>/dev/null
fi

exit 0
