#!/bin/bash
# MoAI PreTool Hook Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai hook pre-tool command.
# Project-local hook: .claude/hooks/moai/pre-tool.sh

# Add Windows dotnet to PATH (required for quality gate on Windows)
if [ -d "/c/Program Files/dotnet" ]; then
	export PATH="/c/Program Files/dotnet:$PATH"
fi

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH
if command -v moai &> /dev/null; then
	exec moai hook pre-tool < "$temp_file" 2>/dev/null
fi

# Try detected Go bin path from initialization
if [ -f "C:/Users/drake.lee/go/bin/moai" ]; then
	exec "C:/Users/drake.lee/go/bin/moai" hook pre-tool < "$temp_file" 2>/dev/null
fi

# Try default ~/go/bin/moai
if [ -f "$HOME/go/bin/moai" ]; then
	exec "$HOME/go/bin/moai" hook pre-tool < "$temp_file" 2>/dev/null
fi

# Try ~/.local/bin/moai (Linux install location)
if [ -f "$HOME/.local/bin/moai" ]; then
	exec "$HOME/.local/bin/moai" hook pre-tool < "$temp_file" 2>/dev/null
fi

# Not found - exit silently (Claude Code handles missing hooks gracefully)
exit 0
