using FluentAssertions;
using HnVue.Common.Abstractions;
using HnVue.Common.Models;
using HnVue.Common.Results;
using HnVue.UI.ViewModels;
using NSubstitute;
using Xunit;

namespace HnVue.UI.Tests;

/// <summary>
/// Unit tests for <see cref="AddPatientProcedureViewModel"/>.
/// SWR-UI-ADD-001 through SWR-UI-ADD-010.
/// </summary>
public sealed class AddPatientProcedureViewModelTests
{
    private static (AddPatientProcedureViewModel Vm, IPatientService PatientService) CreateSut()
    {
        var patientService = Substitute.For<IPatientService>();
        var vm = new AddPatientProcedureViewModel(patientService, Substitute.For<ISecurityContext>());
        return (vm, patientService);
    }

    // ── Constructor tests ────────────────────────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-001")]
    public void Constructor_InitializesWithAutoGeneratedPatientId()
    {
        var (vm, _) = CreateSut();

        vm.PatientId.Should().StartWith("PT", "PatientId should be auto-generated with PT prefix");
        vm.IsPatientIdAutoGenerate.Should().BeTrue();
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-001")]
    public void Constructor_InitializesWithAutoGeneratedAccessionNumber()
    {
        var (vm, _) = CreateSut();

        vm.AccessionNumber.Should().StartWith("ACC", "AccessionNumber should be auto-generated with ACC prefix");
        vm.IsAccNoAutoGenerate.Should().BeTrue();
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-001")]
    public void Constructor_InitializesWithEmptyRequiredFields()
    {
        var (vm, _) = CreateSut();

        vm.PatientName.Should().BeEmpty();
        vm.BirthDate.Should().BeEmpty();
        vm.Gender.Should().BeEmpty();
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-001")]
    public void Constructor_InitializesAvailableProjectionsAndDescriptions()
    {
        var (vm, _) = CreateSut();

        vm.AvailableProjections.Should().NotBeEmpty();
        vm.AvailableDescriptions.Should().NotBeEmpty();
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-001")]
    public void Constructor_SelectedCollectionsAreEmpty()
    {
        var (vm, _) = CreateSut();

        vm.SelectedProjections.Should().BeEmpty();
        vm.SelectedDescriptions.Should().BeEmpty();
    }

    // ── Property change notification tests ──────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-002")]
    public void PatientName_WhenSet_RaisesPropertyChanged()
    {
        var (vm, _) = CreateSut();
        var raised = new List<string?>();
        vm.PropertyChanged += (_, e) => raised.Add(e.PropertyName);

        vm.PatientName = "Kim Chul-Su";

        raised.Should().Contain(nameof(vm.PatientName));
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-002")]
    public void BirthDate_WhenSet_RaisesPropertyChanged()
    {
        var (vm, _) = CreateSut();
        var raised = new List<string?>();
        vm.PropertyChanged += (_, e) => raised.Add(e.PropertyName);

        vm.BirthDate = "1990-01-15";

        raised.Should().Contain(nameof(vm.BirthDate));
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-002")]
    public void Gender_WhenSet_RaisesPropertyChanged()
    {
        var (vm, _) = CreateSut();
        var raised = new List<string?>();
        vm.PropertyChanged += (_, e) => raised.Add(e.PropertyName);

        vm.Gender = "M";

        raised.Should().Contain(nameof(vm.Gender));
    }

    // ── AddProjection command tests ──────────────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-003")]
    public void AddProjectionCommand_AddsProjectionToSelectedList()
    {
        var (vm, _) = CreateSut();

        vm.AddProjectionCommand.Execute("Chest PA");

        vm.SelectedProjections.Should().Contain("Chest PA");
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-003")]
    public void AddProjectionCommand_DoesNotAddDuplicateProjection()
    {
        var (vm, _) = CreateSut();
        vm.AddProjectionCommand.Execute("Chest PA");
        vm.AddProjectionCommand.Execute("Chest PA");

        vm.SelectedProjections.Should().HaveCount(1);
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-003")]
    public void AddProjectionCommand_IgnoresNullOrWhitespace()
    {
        var (vm, _) = CreateSut();
        vm.AddProjectionCommand.Execute(null);
        vm.AddProjectionCommand.Execute("  ");

        vm.SelectedProjections.Should().BeEmpty();
    }

    // ── RemoveProjection command tests ──────────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-004")]
    public void RemoveProjectionCommand_RemovesProjectionFromSelectedList()
    {
        var (vm, _) = CreateSut();
        vm.AddProjectionCommand.Execute("Chest PA");

        vm.RemoveProjectionCommand.Execute("Chest PA");

        vm.SelectedProjections.Should().NotContain("Chest PA");
    }

    // ── AddDescription command tests ─────────────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-005")]
    public void AddDescriptionCommand_AddsDescriptionToSelectedList()
    {
        var (vm, _) = CreateSut();

        vm.AddDescriptionCommand.Execute("Routine");

        vm.SelectedDescriptions.Should().Contain("Routine");
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-005")]
    public void AddDescriptionCommand_ClearsDescriptionInputAfterAdding()
    {
        var (vm, _) = CreateSut();
        vm.DescriptionInput = "Custom Desc";

        vm.AddDescriptionCommand.Execute(null); // uses DescriptionInput

        vm.SelectedDescriptions.Should().Contain("Custom Desc");
        vm.DescriptionInput.Should().BeEmpty();
    }

    // ── ToggleAutoGenerate command tests ─────────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-006")]
    public void ToggleAccNoAutoGenerateCommand_TogglesFlag()
    {
        var (vm, _) = CreateSut();
        vm.IsAccNoAutoGenerate.Should().BeTrue();

        vm.ToggleAccNoAutoGenerateCommand.Execute(null);

        vm.IsAccNoAutoGenerate.Should().BeFalse();
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-006")]
    public void TogglePatientIdAutoGenerateCommand_TogglesFlag()
    {
        var (vm, _) = CreateSut();
        vm.IsPatientIdAutoGenerate.Should().BeTrue();

        vm.TogglePatientIdAutoGenerateCommand.Execute(null);

        vm.IsPatientIdAutoGenerate.Should().BeFalse();
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-006")]
    public void IsPatientIdAutoGenerate_WhenToggledOn_RegeneratesPatientId()
    {
        var (vm, _) = CreateSut();
        vm.TogglePatientIdAutoGenerateCommand.Execute(null); // disable
        vm.PatientId = "MANUAL-123";

        vm.TogglePatientIdAutoGenerateCommand.Execute(null); // re-enable

        vm.PatientId.Should().StartWith("PT", "re-enabling auto-generate should regenerate the ID");
    }

    // ── Cancel command tests ─────────────────────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-007")]
    public void CancelCommand_RaisesCancelledEvent()
    {
        var (vm, _) = CreateSut();
        var cancelled = false;
        vm.Cancelled += (_, _) => cancelled = true;

        vm.CancelCommand.Execute(null);

        cancelled.Should().BeTrue();
    }

    // ── Save command validation tests ────────────────────────────────────────

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-008")]
    public async Task SaveCommand_WhenPatientNameEmpty_SetsErrorMessage()
    {
        var (vm, _) = CreateSut();
        vm.PatientName = string.Empty;
        vm.BirthDate = "1990-01-01";
        vm.Gender = "M";
        vm.AddProjectionCommand.Execute("Chest PA");

        vm.SaveCommand.Execute(null);
        await Task.Delay(100); // allow async to complete

        vm.ErrorMessage.Should().Contain("Patient Name");
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-008")]
    public async Task SaveCommand_WhenBirthDateEmpty_SetsErrorMessage()
    {
        var (vm, _) = CreateSut();
        vm.PatientName = "Kim Chul-Su";
        vm.BirthDate = string.Empty;
        vm.Gender = "M";
        vm.AddProjectionCommand.Execute("Chest PA");

        vm.SaveCommand.Execute(null);
        await Task.Delay(100);

        vm.ErrorMessage.Should().Contain("Birth Date");
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-008")]
    public async Task SaveCommand_WhenNoProjectionsSelected_SetsErrorMessage()
    {
        var (vm, _) = CreateSut();
        vm.PatientName = "Kim Chul-Su";
        vm.BirthDate = "1990-01-01";
        vm.Gender = "M";
        // SelectedProjections is empty

        vm.SaveCommand.Execute(null);
        await Task.Delay(100);

        vm.ErrorMessage.Should().Contain("Procedure");
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-009")]
    public async Task SaveCommand_WhenValidAndServiceSucceeds_RaisesSaveCompleted()
    {
        var (vm, patientService) = CreateSut();
        vm.PatientName = "Kim Chul-Su";
        vm.BirthDate = "1990-01-15";
        vm.Gender = "M";
        vm.AddProjectionCommand.Execute("Chest PA");

        var expectedRecord = new PatientRecord(
            PatientId: vm.PatientId,
            Name: "Kim Chul-Su",
            DateOfBirth: new DateOnly(1990, 1, 15),
            Sex: "M",
            IsEmergency: false,
            CreatedAt: DateTimeOffset.UtcNow,
            CreatedBy: string.Empty);

        patientService.RegisterAsync(Arg.Any<PatientRecord>())
            .Returns(Result.Success(expectedRecord));

        var saveCompleted = false;
        vm.SaveCompleted += (_, _) => saveCompleted = true;

        vm.SaveCommand.Execute(null);
        await Task.Delay(200);

        saveCompleted.Should().BeTrue("SaveCompleted event should be raised on success");
    }

    [Fact]
    [Trait("SWR", "SWR-UI-ADD-010")]
    public async Task SaveCommand_WhenServiceFails_SetsErrorMessage()
    {
        var (vm, patientService) = CreateSut();
        vm.PatientName = "Kim Chul-Su";
        vm.BirthDate = "1990-01-15";
        vm.Gender = "M";
        vm.AddProjectionCommand.Execute("Chest PA");

        patientService.RegisterAsync(Arg.Any<PatientRecord>())
            .Returns(Result.Failure<PatientRecord>(ErrorCode.DatabaseError, "DB unavailable"));

        vm.SaveCommand.Execute(null);
        await Task.Delay(200);

        vm.ErrorMessage.Should().NotBeNullOrEmpty("error message should be set on service failure");
    }

    // ── Explicit interface implementation tests ─────────────────────────────

    [Fact]
    public void IViewModelBase_IsLoading_MapsToIsLoading()
    {
        var (vm, _) = CreateSut();
        vm.IsLoading = false;
        ((HnVue.UI.Contracts.ViewModels.IViewModelBase)vm).IsLoading.Should().BeFalse();

        vm.IsLoading = true;
        ((HnVue.UI.Contracts.ViewModels.IViewModelBase)vm).IsLoading.Should().BeTrue();
    }

    [Fact]
    public void IAddPatientProcedureViewModel_AddProjectionCommand_ReturnsAddProjectionCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).AddProjectionCommand
            .Should().BeSameAs(vm.AddProjectionCommand);
    }

    [Fact]
    public void IAddPatientProcedureViewModel_RemoveProjectionCommand_ReturnsRemoveProjectionCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).RemoveProjectionCommand
            .Should().BeSameAs(vm.RemoveProjectionCommand);
    }

    [Fact]
    public void IAddPatientProcedureViewModel_AddDescriptionCommand_ReturnsAddDescriptionCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).AddDescriptionCommand
            .Should().BeSameAs(vm.AddDescriptionCommand);
    }

    [Fact]
    public void IAddPatientProcedureViewModel_RemoveDescriptionCommand_ReturnsRemoveDescriptionCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).RemoveDescriptionCommand
            .Should().BeSameAs(vm.RemoveDescriptionCommand);
    }

    [Fact]
    public void IAddPatientProcedureViewModel_ToggleAccNoAutoGenerateCommand_ReturnsToggleAccNoAutoGenerateCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).ToggleAccNoAutoGenerateCommand
            .Should().BeSameAs(vm.ToggleAccNoAutoGenerateCommand);
    }

    [Fact]
    public void IAddPatientProcedureViewModel_TogglePatientIdAutoGenerateCommand_ReturnsTogglePatientIdAutoGenerateCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).TogglePatientIdAutoGenerateCommand
            .Should().BeSameAs(vm.TogglePatientIdAutoGenerateCommand);
    }

    [Fact]
    public void IAddPatientProcedureViewModel_SaveCommand_ReturnsSaveCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).SaveCommand
            .Should().BeSameAs(vm.SaveCommand);
    }

    [Fact]
    public void IAddPatientProcedureViewModel_CancelCommand_ReturnsCancelCommand()
    {
        var (vm, _) = CreateSut();
        ((HnVue.UI.Contracts.ViewModels.IAddPatientProcedureViewModel)vm).CancelCommand
            .Should().BeSameAs(vm.CancelCommand);
    }

    // ── Additional edge case tests ──────────────────────────────────────────────

    [Fact]
    public void RemoveProjectionCommand_WithNull_DoesNotThrow()
    {
        var (vm, _) = CreateSut();
        vm.AddProjectionCommand.Execute("Chest PA");

        vm.RemoveProjectionCommand.Execute(null);

        vm.SelectedProjections.Should().ContainSingle("Chest PA", "removing null should not remove anything");
    }

    [Fact]
    public void RemoveProjectionCommand_WithWhitespace_DoesNotThrow()
    {
        var (vm, _) = CreateSut();
        vm.AddProjectionCommand.Execute("Chest PA");

        vm.RemoveProjectionCommand.Execute("  ");

        vm.SelectedProjections.Should().ContainSingle("Chest PA", "removing whitespace should not remove anything");
    }

    [Fact]
    public void RemoveDescriptionCommand_WithNull_DoesNotThrow()
    {
        var (vm, _) = CreateSut();
        vm.AddDescriptionCommand.Execute("Routine");

        vm.RemoveDescriptionCommand.Execute(null);

        vm.SelectedDescriptions.Should().ContainSingle("Routine", "removing null should not remove anything");
    }

    [Fact]
    public void AddDescriptionCommand_WithWhitespaceOnly_DoesNotAdd()
    {
        var (vm, _) = CreateSut();
        vm.DescriptionInput = "   ";

        vm.AddDescriptionCommand.Execute(null);

        vm.SelectedDescriptions.Should().BeEmpty();
    }

    [Fact]
    public void IsAccNoAutoGenerate_WhenToggledOn_RegeneratesAccessionNumber()
    {
        var (vm, _) = CreateSut();

        vm.ToggleAccNoAutoGenerateCommand.Execute(null); // disable
        vm.AccessionNumber = "MANUAL-ACC-123";

        // Add a delay to ensure timestamp changes (1 second to be safe)
        Thread.Sleep(1000);

        vm.ToggleAccNoAutoGenerateCommand.Execute(null); // re-enable

        vm.AccessionNumber.Should().StartWith("ACC", "re-enabling auto-generate should regenerate the accession number");
    }
}
