// <auto-generated />
using System;
using HnVue.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HnVue.Data.Migrations
{
    [DbContext(typeof(HnVueDbContext))]
    partial class HnVueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HnVue.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<string>("EntryId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimestampOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TimestampTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("TimestampTicks");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HnVue.Data.Entities.DoseRecordEntity", b =>
                {
                    b.Property<string>("DoseId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("Dap")
                        .HasColumnType("REAL");

                    b.Property<double>("EffectiveDose")
                        .HasColumnType("REAL");

                    b.Property<double>("Ei")
                        .HasColumnType("REAL");

                    b.Property<int>("RecordedAtOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RecordedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("DoseId");

                    b.HasIndex("StudyInstanceUid");

                    b.ToTable("DoseRecords");
                });

            modelBuilder.Entity("HnVue.Data.Entities.ImageEntity", b =>
                {
                    b.Property<string>("ImageId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("AcquiredAtOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcquiredAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("StudyInstanceUid");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("HnVue.Data.Entities.PatientEntity", b =>
                {
                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("CreatedAtOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DateOfBirth")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmergency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.HasIndex("Name");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HnVue.Data.Entities.StudyEntity", b =>
                {
                    b.Property<string>("StudyInstanceUid")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessionNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyPart")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyDateOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StudyDateTicks")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudyInstanceUid");

                    b.HasIndex("PatientId");

                    b.ToTable("Studies");
                });

            modelBuilder.Entity("HnVue.Data.Entities.UpdateHistoryEntity", b =>
                {
                    b.Property<int>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstalledBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("UpdateId");

                    b.HasIndex("FromVersion");

                    b.HasIndex("Timestamp");

                    b.HasIndex("ToVersion");

                    b.ToTable("UpdateHistories");
                });

            modelBuilder.Entity("HnVue.Data.Entities.UserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastLoginAtOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginAtTicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuickPinFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuickPinHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long?>("QuickPinLockedUntilTicks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HnVue.Data.Entities.DoseRecordEntity", b =>
                {
                    b.HasOne("HnVue.Data.Entities.StudyEntity", "Study")
                        .WithMany("DoseRecords")
                        .HasForeignKey("StudyInstanceUid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("HnVue.Data.Entities.ImageEntity", b =>
                {
                    b.HasOne("HnVue.Data.Entities.StudyEntity", "Study")
                        .WithMany("Images")
                        .HasForeignKey("StudyInstanceUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Study");
                });

            modelBuilder.Entity("HnVue.Data.Entities.StudyEntity", b =>
                {
                    b.HasOne("HnVue.Data.Entities.PatientEntity", "Patient")
                        .WithMany("Studies")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HnVue.Data.Entities.PatientEntity", b =>
                {
                    b.Navigation("Studies");
                });

            modelBuilder.Entity("HnVue.Data.Entities.StudyEntity", b =>
                {
                    b.Navigation("DoseRecords");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
